### ISSUE TITLE
Anchor Popover

### ISSUE THREAD

**Issue by magital15** [collab-ui/collab-ui-react#138]
![screen shot 2018-08-15 at 10 26 42 am](https://user-images.githubusercontent.com/10239711/44166366-185ff500-a080-11e8-8b32-12e0e9324dff.png)

<img width="456" alt="screen shot 2018-08-10 at 4 26 23 pm" src="https://user-images.githubusercontent.com/10239711/44164758-c026f400-a07b-11e8-8758-8de598193d21.png">

The popover content is going from `<List .../>` to `<span><DialPad></span>` and the popover is being displaced, where before it was placed properly offset from its Button child.

web-client was previously using the Popover from web-client-components, and that had specific logic to place the Popover at a specific location relative to the anchor element. Is there another solution intended for collab-ui Popover?

**Comment by pauljeter** [comment]
It looks like the dialpad should be a modal instead of a popover? Let's discuss in our Webex Teams space.
