### ISSUE TITLE
Error with ListItem ID mismatch in universal/isomorphic app

### ISSUE THREAD

**Issue by robinmakinson** [collab-ui/collab-ui-react#146]
The ListItem always generates a unique ID for itself using lodash's unique function. Even if you pass in a ID prop, it'll run it through lodash's unique function too. 

The issue with this is that in a universal/isomorphic app, the component is rendered on the server and the client. Because the component's ID is generated using lodash's unique function once on the server and once on the client, the IDs do not match and a warning is shown about the mismatch. I think the server-rendered version of code may be discarded in favor of client-side generated code, which is not performant.

**Comment by pauljeter** [comment]
Putting this in our backlog to be prioritized.
