### ISSUE TITLE
Interface for select is not clear

### ISSUE THREAD

**Issue by cruzj6** [collab-ui/collab-ui-react#147]
It was difficult to determine the intended usage of the Select and SelectOption components without digging into the code. 

When selecting an option, the event given to the onClick callback does not include the value of the SelectOption I selected, so it's unclear what value my onClick callback is intended to use as the identifier.

I think the interface should be similar to the basic react select component interface, or it should be documented.

**Comment by pauljeter** [comment]
Thank you for bringing this to our attention. We are aware that our current documentation is limited and insufficient. We are currently working on a new documentation site that will cover how to use the components and the available props. Please bear with us while we work to improve our design system. Thanks.
