### ISSUE TITLE
Documentation is not clear

### ISSUE THREAD

**Issue by chinmaymahajan** [collab-ui/collab-ui-react#156]
The overall documentation is not clear so it's difficult for us to use the toolkit.
We have experienced lot of problems in using toolkit because of lack of documentation so we have to jump in the code to look how to use certain components, the official site is also down sometimes.

**Comment by pauljeter** [comment]
Thank you for bringing this to our attention. We are aware that our current documentation is limited and insufficient. We are currently working on a new documentation site that will cover how to use the components and the available props. Please bear with us while we work to improve our design system. Thanks.
