### ISSUE TITLE
Coachmark anchor 3 gets active even when not clicked.

### ISSUE THREAD

**Issue by VinayakPanchal** [collab-ui/collab-ui-react#162]
<img width="1680" alt="screen shot 2018-08-31 at 10 33 01 am" src="https://user-images.githubusercontent.com/8220395/45096923-a4999100-b0ef-11e8-9278-501d12ff6496.png">

I found a bug in collab-ui-react. I clicked on Coachmark anchor 1 then coachmark anchor 2 then back to coachmark anchor 1, I see coachmark anchor 3 is active as well.

**Comment by pauljeter** [comment]
This is an issue with the documentation, not the component itself. Thank you for bringing this to our attention. We are aware that our current documentation is limited and insufficient. We are currently working on a new documentation site that will cover how to use the components and the available props. Please bear with us while we work to improve our design system. Thanks.
