### ISSUE TITLE
ListItemMeeting style need to be changed

### ISSUE THREAD

**Issue by stanjiawang** [collab-ui/collab-ui-react#164]
The padding  of the left section contains Date & Time is not enough, which caused the overlap with meeting title. Please see the screenshot below.

![screen shot 2018-09-06 at 11 34 48 am](https://user-images.githubusercontent.com/14055396/45177831-e64a3a80-b1c8-11e8-8772-ce723fea1a00.png)
![screen shot 2018-09-06 at 11 34 29 am](https://user-images.githubusercontent.com/14055396/45177832-e64a3a80-b1c8-11e8-8e35-c4958cca5904.png)

Please see VD below:
https://cisco.invisionapp.com/share/P3M83ILAWSE#/screens/306207271
![screen shot 2018-09-06 at 11 38 48 am](https://user-images.githubusercontent.com/14055396/45178022-6ffa0800-b1c9-11e8-912a-36ee4b8d5065.png)
![screen shot 2018-09-06 at 11 39 03 am](https://user-images.githubusercontent.com/14055396/45178029-78524300-b1c9-11e8-8fc4-be087299d93c.png)

**Comment by stanjiawang** [comment]
@bfbiggs Could you please fix it ASAP? Our IA8 is ETF today. Thanks a lot!

**Comment by pauljeter** [comment]
Not an issue
