### ISSUE TITLE
Changing the time in Timepicker by typing doesn't apply until blur

### ISSUE THREAD

**Issue by cruzj6** [collab-ui/collab-ui-react#169]
When typing the minutes or hours the onChange callback is not called until you blur the input, which is inconsistent with using the arrows to change the time.

**Comment by pauljeter** [comment]
This is by design. When the time is typed, we do not know if they are done typing after the 1st digit or if there will be a second digit. When using the arrows, we know the increment so we can call the onChange immediately.
