### ISSUE TITLE
ContentItem issues

### ISSUE THREAD

**Issue by aimeex3** [collab-ui/collab-ui-react#186]
Hey there! Before you post an issue here, did you try reporting this to the "Collab UI Q&A" space in Webex Teams? Please ask about your issue there before creating a new GitHub issue.

**I'm submitting a ...**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/collab-ui/collab-ui-react/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Component Affected**
ContentItem

**Current behavior**
1. title overlaps with subtitle
2. no image click handler
3. blank space when no title is present and subtitle is present
4. Failed text is hardcoded https://github.com/collab-ui/collab-ui-react/blob/master/src/lib/ContentItem/index.js#L37
5. gif badge does not show up on top right of gif images

**Expected/desired behavior**
1. title should not overlap with subtitle. perhaps truncate text with ellipses with hover to show full file name (native tooltip `title` prop)
2. have click handler on image with indication that item is clickable (pointer cursor, maybe change color of border) . also make sure click handler does not trigger when clicking on buttons in actionNode
3. Should the subtitle take up the space if there is no title?
4. Allow failed text to be passed in
5. gif badge should show up on top right of gif images

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via images or video.

![screen shot 2018-10-19 at 2 44 15 pm](https://user-images.githubusercontent.com/819823/47245282-7f19cb80-d3ad-11e8-9e1f-e55a32ee2463.png)

![screen shot 2018-10-19 at 2 54 19 pm](https://user-images.githubusercontent.com/819823/47245714-41b63d80-d3af-11e8-91ff-d1e7eb2afe4b.png)

![screen shot 2018-10-22 at 12 13 03 pm](https://user-images.githubusercontent.com/819823/47313501-f50f7400-d5f3-11e8-9627-a22392a5817b.png)

**Please tell us about your environment:**

* **Toolkit Version version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by daanishnasir** [comment]
- [ ] failedText prop

**Comment by pauljeter** [comment]
Fixed in #187
